#!/bin/bash
#PBS -q workq
#PBS -l nodes=1:ppn=20
#PBS -l walltime=24:00:00
#PBS -o SNPMNP_test_output
#PBS -N SNPMNP_test_052620
#PBS -A loni_gupd_redos

module load java/1.8.0
/home/sydnij/packages/gatk-4.1.5.0/gatk SelectVariants --variant /work/sydnij/GUPD_kraken_rangewide.vcf -R /work/sydnij/pdogkrakengenome/pilon_pdog_kraken_nothuman_1308.fasta --output /work/sydnij/GUPD_kraken_rangewide_SNP_MNP.vcf -select-type SNP -select-type MNP --exclude-non-variants true --set-filtered-gt-to-nocall true
