#!/bin/bash
#PBS -q workq
#PBS -l nodes=1:ppn=20
#PBS -l walltime=72:00:00
#PBS -o picardtools_pcr_output
#PBS -N picardtools_pcr_050720
#PBS -A loni_repeats03

module load  java/1.8.0
cd $PBS_O_WORKDIR
mkdir -p tmp

for i in /work/sydnij/bwa_mem/*.tag.bam; 
do
	java -Xmx4g -jar /home/sydnij/packages/picard/picard.jar \
	MarkDuplicates INPUT=$i OUTPUT=${i%.tag.bam}.rmdup.bam MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=6000 MAX_RECORDS_IN_RAM=1000000 TMP_DIR=$PWD/tmp \
	METRICS_FILE=${i%.tag.bam}.rmdup.metrics ASSUME_SORTED=true;
done

